### ISSUE TITLE
OMGooooooooooooh sound????

### ISSUE THREAD

**Issue by Reeenatu** [DapperMickie/odablock-sounds#17]
Can we somehow get the classic OMGooooooooooooooooooh sound?!? This is by far the best one, idk why its not included

**Comment by DapperMickie** [comment]
@Reeenatu When should this sound play?

**Comment by Reeenatu** [comment]
> @Reeenatu When should this sound play?

I always wanted to use it when receiving a pet, and a few other ppl might wanna use it when receiving a rare drop.

**Comment by DapperMickie** [comment]
@Reeenatu We already have sounds for both of those, you could look at the [README](https://github.com/DapperMickie/odablock-sounds/blob/master/README.md) to see how you can customize sounds on your end.

**Comment by Reeenatu** [comment]
> @Reeenatu We already have sounds for both of those, you could look at the [README](https://github.com/DapperMickie/odablock-sounds/blob/master/README.md) to see how you can customize sounds on your end.
 Oh yeah, ik how to do that, my only issue is that i dont know where to find the audio file of him saying that. If you could sort me with that file, id be very grateful

**Comment by DapperMickie** [comment]
@Reeenatu the README has a section with links to code and all the sounds played for a certain action:
https://github.com/DapperMickie/odablock-sounds/blob/master/README.md#currently-implemented-sounds-include
