### ISSUE TITLE
Sound Files not all downloading 

### ISSUE THREAD

**Issue by Didntnut** [DapperMickie/odablock-sounds#23]
after installing plugin most sounds do not work, looking into the file only 6 sound files are in the folder
![plugin](https://github.com/DapperMickie/odablock-sounds/assets/163369836/0c5904f0-1a00-45fd-9376-90058ce40e73)

**Comment by DapperMickie** [comment]
Please delete all the files in the folder ande restart your client, that should fix it. I pushed an update for the sound system earlier today but we're waiting on runelite approval (can take a few days to weeks). If this happens again please let me know.

**Comment by DapperMickie** [comment]
Plugin update came out today, should fix this problem either way!
