### ISSUE TITLE
Emoji's Disable

### ISSUE THREAD

**Issue by sussledust** [DapperMickie/odablock-sounds#63]
I like just about everything there is to offer in the plugin EXCEPT that smiley faces and such are automatically Odablock's small picture of most likely Twitch/Kick emoji's but still. I don't think it deserves to override a smiley or sad face in a chat that has nothing to do with him.

**Comment by bas-clockassist** [comment]
Agree should make this an option

**Comment by DapperMickie** [comment]
This has been fixed in the latest update. Restart your client to update the plugin.
